version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: bash -lc 'nohup hbbs -r 0.0.0.0 > ./hbbs.log 2>&1 &; nohup hbbr > ./hbbr.log 2>&1 &'
    volumes:
      - "./workdir:/root"
    network_mode: "host"
    restart: unless-stopped
